from datetime import datetime

from sqlalchemy import Column, DateTime, Integer, String, Text

from app.database import Base


class LogEvent(Base):
    """
    Stores individual security events / logs.
    """

    __tablename__ = "logs"

    id = Column(Integer, primary_key=True, index=True)
    source = Column(String(100), index=True)
    event_type = Column(String(50), index=True)  # e.g. login, access, error
    message = Column(Text)
    severity = Column(String(20), index=True)  # e.g. info, warning, error, critical
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)

    def __repr__(self) -> str:  # magic method example
        return f"<LogEvent id={self.id} severity={self.severity} source={self.source!r}>"


class Alert(Base):
    """
    Stores alerts generated by detection rules.
    """

    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True)
    rule_name = Column(String(100), index=True)
    severity = Column(String(20), index=True)
    description = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    source = Column(String(100), nullable=True)

    def __repr__(self) -> str:  # magic method example
        return f"<Alert id={self.id} rule={self.rule_name!r} severity={self.severity}>"

